import Image from "next/image";

import {
  AnimatedLink,
  FadeIn,
  StaggerContainer,
  StaggerItem,
} from "@/components/motion";

const paragraphClassName =
  "text-sm leading-[24px] text-[#171717]/85 sm:text-base";

const introParagraphs = [
  "For StoryTree, Web3 and blockchain technology are the practical infrastructure we use to solve real-world economic problems in African cinema.",
  "Traditionally, film financing is a closed-door game, accounting is notoriously opaque, and piracy drains a project’s revenue before it can scale. By embedding blockchain architecture into our ecosystem, we restore financial transparency, protect intellectual property, and give ownership of the pipeline back to the creators and the community.",
  "Here is how our technology actively works to build a sustainable industry:",
];

const features = [
  {
    title: "1. Transparent Crowdfunding & Local Onboarding",
    description:
      "We believe that financing shouldn't be restricted to institutional gatekeepers. Through StoryTree, community members can directly fund projects they believe in using their local currencies. The underlying blockchain technology acts as an unalterable, transparent ledger. The moment a contribution is made in local currency, the transaction is recorded on-chain and seamlessly converted into fractionalized token ownership. This ensures every backer has a verifiable, auditable stake in the film’s success, completely eliminating the opaque accounting structures typical of traditional studio models.",
    imageSrc: "/block1.png",
  },
  {
    title: "2. Decentralized Governance (The FAN Token)",
    description:
      "Our community doesn't just watch content; they help steer it. Our ecosystem is powered by the FAN token, which functions as a governance mechanism. Once independent concepts or internal competition scripts are streamlined by our Advisory Board for quality and viability, the final selection goes to a community vote. By holding and utilizing FAN tokens, members directly influence which projects are greenlit for production and how final products are distributed. This aligns the interests of the audience and the creators long before a single frame is shot.",
    imageSrc: "/block2.png",
  },
  {
    title: "3. Anti-Piracy & Smart Distribution",
    description:
      "The biggest threat to independent African cinema is the unauthorized distribution and leaking of content. Traditional digital distribution leaves independent filmmakers highly vulnerable to revenue loss. We use blockchain architecture to secure access and verify user credentials. Whether it is a preview link for our FilmClub meetings or a global digital release, content is delivered via secure, encrypted links tied to ecosystem membership. Because access rights are verified on-chain, we can track distribution securely, prevent unauthorized sharing, and ensure that the economic value generated by a film flows directly back to the creators and the investors who funded it. By leveraging Web3, we are moving African cinema into a secure, borderless, and scalable digital ecosystem.",
    imageSrc: "/block3.png",
  },
];

export function HowItWorksWeb3() {
  return (
    <section
      id="web3-blockchain"
      className="relative z-10 scroll-mt-20 py-16 font-inter md:py-28 lg:scroll-mt-[6.5rem] lg:py-32"
      style={{
        background:
          "linear-gradient(180deg, #FDFBF7 0%, #F5EDD8 45%, #E2B45F 100%)",
      }}
    >
      <div className="mx-auto max-w-[950px] px-4 text-center md:px-6 lg:px-8">
        <FadeIn>
          <Image
            src="/storyTree.svg"
            alt="Story Tree"
            width={160}
            height={40}
            className="mx-auto h-8 w-auto brightness-0 md:h-9"
          />

          <h2 className="mx-auto mt-1 max-w-[1000px] text-[26px] font-bold leading-tight text-[#171717] sm:text-[32px] md:text-[40px]">
            Web3 &amp; Blockchain: The Technology of StoryTree
          </h2>
        </FadeIn>

        <StaggerContainer className="mt-8  text-left sm:mt-10 md:mt-12">
          {introParagraphs.map((paragraph) => (
            <StaggerItem key={paragraph.slice(0, 32)}>
              <p className={paragraphClassName}>{paragraph}</p>
            </StaggerItem>
          ))}
        </StaggerContainer>

        <div className="mt-10 space-y-10 text-left sm:mt-12 sm:space-y-12 md:mt-16 md:space-y-16">
          {features.map((feature, index) => (
            <FadeIn key={feature.title} delay={0.05 + index * 0.05}>
              <h3 className="text-base font-semibold text-[#171717] sm:text-lg md:text-xl">
                {feature.title}
              </h3>
              <p className={`mt-4 ${paragraphClassName}`}>{feature.description}</p>
              <Image
                src={feature.imageSrc}
                alt="Film crew on a beach at golden hour"
                width={1176}
                height={308}
                className="mt-6 h-auto w-full rounded-lg md:mt-8 md:rounded-xl"
              />
            </FadeIn>
          ))}
        </div>

        <FadeIn delay={0.2} className="mt-10 text-center sm:mt-12 md:mt-16">
          <AnimatedLink
            href="/join"
            className="inline-block rounded-[8px] border border-[#171717] px-8 py-3 text-sm font-medium text-[#171717]"
          >
            Join The Community
          </AnimatedLink>
        </FadeIn>
      </div>
    </section>
  );
}
